name: Release pipeline

on:
  workflow_dispatch:
  
  pull_request:
      types:
        - opened
        - synchronize
      branches:
        - main

jobs:
  release-pipeline:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: "Set up CLI"
        uses: databricks/setup-cli@main
      #----------------------------------------------
      #              deploy bundle to Staging
      #----------------------------------------------
      - name: "validate bundle"
        run: databricks bundle validate
      - name: "deploy bundle"
        run: databricks bundle deploy
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID:  ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET:  ${{ secrets.DATABRICKS_CLIENT_SECRET }}
